// <auto-generated />
namespace QuirkyBookRental.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class noseperquenofunciona : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(noseperquenofunciona));
        
        string IMigrationMetadata.Id
        {
            get { return "202206091436322_noseperquenofunciona"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
